---
dependencies:
  - role: docker

galaxy_info:
  author: Cosmo Tech
  description: SonarQube installation and configuration
  company: Cosmo Tech
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - sonarqube
    - analysis
    - quality
