---
# SonarQube role tasks

- name: Setup SonarQube directories
  import_tasks: directories.yml

- name: Configure SonarQube
  import_tasks: configure.yml

- name: Deploy SonarQube
  import_tasks: deploy.yml
