---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: sonarqube-test
    box: debian/bookworm64
    memory: 4096  # SonarQube needs at least 4GB
    cpus: 2
    interfaces:
      - network_name: private_network
        ip: 192.168.56.21
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--natdnshostresolver1', 'on']"
    instance_raw_config_args:
      - "vm.provision 'shell', inline: 'sysctl -w vm.max_map_count=262144'"
provisioner:
  name: ansible
  env:
    SONARQUBE_DB_PASSWORD: testpassword
  inventory:
    host_vars:
      sonarqube-test:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint
  yamllint .
