---
# Install SonarQube with docker

- name: Install required packages
  apt:
    name:
      - docker.io
    state: present
    update_cache: true
  become: true

- name: Create SonarQube directory
  file:
    path: "/opt/sonarqube"
    state: directory
    mode: '0755'
  become: true

- name: Create Docker named volumes
  docker_volume:
    name: "{{ item }}"
    state: present
  loop:
    - sonarqube_data
    - sonarqube_logs
    - sonarqube_extensions
  become: true

- name: Pull SonarQube image
  docker_image:
    name: sonarqube:community
    source: pull
  become: true

- name: Create and start SonarQube container
  docker_container:
    name: sonarqube
    image: sonarqube:community
    state: started
    restart_policy: always
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    env:
      SONAR_JDBC_URL: "jdbc:postgresql//localhost:5432/sonarqube"
      SONAR_JDBC_USERNAME: "{{ postgresql_user }}"
      SONAR_JDBC_PASSWORD: "{{ postgresql_password }}"
  become: true

- name: Wait for SonarQube to be available
  uri:
    url: "http://localhost:9000"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  become: false
