---
galaxy_info:
  author: Cosmo-Tech
  description: Role to install debugging tools (htop, vim, ripgrep, bat)
  company: Cosmo-Tech
  
  license: MIT
  
  min_ansible_version: 2.9
  
  platforms:
    - name: Debian
      versions:
        - bookworm  # Debian 12
    - name: Ubuntu
      versions:
        - focal     # Ubuntu 20.04
        - jammy     # Ubuntu 22.04
  
  galaxy_tags:
    - debug
    - tools
    - development
    - system

dependencies: []
