---
# Debug Tools role tasks

- name: Install common debugging tools
  ansible.builtin.package:
    name: 
      - htop
      - vim
    state: present
  become: true

- name: Check if ripgrep is available in package repositories
  ansible.builtin.command:
    cmd: apt-cache search --names-only "^ripgrep$"
  register: ripgrep_available
  changed_when: false
  failed_when: false
  when: ansible_os_family == "Debian"

- name: Install ripgrep
  ansible.builtin.package:
    name: "{{ 'ripgrep' if ripgrep_available.rc == 0 or ansible_os_family != 'Debian' else debug_tools_ripgrep_alt_package }}"
    state: present
  become: true

- name: Check if bat is available in package repositories
  ansible.builtin.command:
    cmd: apt-cache search --names-only "^bat$"
  register: bat_available
  changed_when: false
  failed_when: false
  when: ansible_os_family == "Debian"

- name: Install bat
  ansible.builtin.package:
    name: "{{ 'bat' if bat_available.rc == 0 or ansible_os_family != 'Debian' else debug_tools_bat_alt_package }}"
    state: present
  become: true

- name: Create bat symlink if installed as batcat
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: /usr/local/bin/bat
    state: link
  become: true
  when: 
    - ansible_os_family == "Debian"
    - bat_available.rc != 0
    - debug_tools_bat_alt_package == "batcat"
    - debug_tools_create_bat_symlink | bool

- name: Install additional debugging tools
  ansible.builtin.package:
    name: "{{ debug_tools_additional_packages }}"
    state: present
  become: true
  when: debug_tools_additional_packages | length > 0
