---
- name: Verify
  hosts: all
  become: false
  tasks:
    - name: Check if htop is installed
      ansible.builtin.command:
        cmd: which htop
      register: htop_check
      changed_when: false
      failed_when: htop_check.rc != 0

    - name: Check if vim is installed
      ansible.builtin.command:
        cmd: which vim
      register: vim_check
      changed_when: false
      failed_when: vim_check.rc != 0

    - name: Check if ripgrep is installed
      ansible.builtin.command:
        cmd: which rg
      register: rg_check
      changed_when: false
      failed_when: rg_check.rc != 0

    - name: Check if bat is installed (either bat or batcat)
      ansible.builtin.shell:
        cmd: which bat || which batcat
      register: bat_check
      changed_when: false
      failed_when: bat_check.rc != 0

    - name: Check if additional tool (lsof) is installed
      ansible.builtin.command:
        cmd: which lsof
      register: lsof_check
      changed_when: false
      failed_when: lsof_check.rc != 0

    - name: Verify all tools are working
      ansible.builtin.debug:
        msg: "All debugging tools are installed and available"
      when: 
        - htop_check.rc == 0
        - vim_check.rc == 0
        - rg_check.rc == 0
        - bat_check.rc == 0
        - lsof_check.rc == 0
