---
# SonarQube role default variables
sonarqube_version: "latest"
sonarqube_port: "9000"

# Directories
sonarqube_base_dir: "/opt/sonarqube"
sonarqube_data_dir: "{{ sonarqube_base_dir }}/data"
sonarqube_extensions_dir: "{{ sonarqube_base_dir }}/extensions"
sonarqube_logs_dir: "{{ sonarqube_base_dir }}/logs"
sonarqube_temp_dir: "{{ sonarqube_base_dir }}/temp"

# Database connection
sonarqube_db_user: "{{ postgresql_user }}"
sonarqube_db_password: "{{ postgresql_password }}"
sonarqube_db_name: "{{ postgresql_db }}"
sonarqube_db_schema: "{{ postgresql_schema }}"
sonarqube_db_host: "host.docker.internal"  # Special Docker hostname to access host machine
sonarqube_db_port: "5432"
