---
# SonarQube role default variables
sonarqube_version: "2025.1"  # Latest stable version
sonarqube_port: "9000"

# Directories
sonarqube_base_dir: "/opt/sonarqube"
sonarqube_data_dir: "{{ sonarqube_base_dir }}/data"
sonarqube_extensions_dir: "{{ sonarqube_base_dir }}/extensions"
sonarqube_logs_dir: "{{ sonarqube_base_dir }}/logs"
sonarqube_temp_dir: "{{ sonarqube_base_dir }}/temp"
sonarqube_install_dir: "{{ sonarqube_base_dir }}/sonarqube-{{ sonarqube_version }}"

# Database connection
sonarqube_db_user: "{{ postgresql_user }}"
sonarqube_db_password: "{{ postgresql_password }}"
sonarqube_db_name: "{{ postgresql_db }}"
sonarqube_db_schema: "{{ postgresql_schema }}"
sonarqube_db_host: "localhost"  # Direct connection to local PostgreSQL
sonarqube_db_port: "5432"

# Java options
sonarqube_java_opts: "-Xmx2048m -Xms2048m"
