---
# Main playbook for SonarQube installation

- name: Install debugging tools
  hosts: sonarqube
  become: true
  roles:
    - debug_tools

- name: Install and configure Docker
  hosts: sonarqube
  become: true
  roles:
    - docker

- name: Install and configure PostgreSQL for SonarQube
  hosts: sonarqube
  become: true
  roles:
    - postgresql

- name: Install and configure SonarQube
  hosts: sonarqube
  become: true
  roles:
    - sonarqube
