---
# Main playbook for SonarQube installation

- name: Install Docker
  hosts: sonarqube
  become: true
  roles:
    - docker

- name: Install PostgreSQL
  hosts: sonarqube
  become: true
  roles:
    - postgresql

- name: Install sonarqube with Docker
  hosts: sonarqube
  become: true
  roles:
    - sonarqube_docker
