---
- name: Converge
  hosts: all
  become: true
  vars:
    postgresql_version: "15"
    postgresql_user: "sonarqube"
    postgresql_password: "{{ lookup('env', 'SONARQUBE_DB_PASSWORD') }}"
    postgresql_db: "sonarqube"
    postgresql_schema: "sonarqube"

  tasks:
    - name: Include PostgreSQL role
      include_role:
        name: postgresql
